---
title: Kirigami Stealth Bumper
description: an RGB-Powered front-bed mount for the Voron V0 with Kirigami Bed Frame
mod_version: 1
discord_username: mapleleafmakers
cad:
- CAD/stealth_bumper.step
images:
- Images/photo.jpg
- Images/render.png
printer_compatibility:
- V0
